# PostgreSQL Veritaban? Ba?lant? Ayarlar?
spring.datasource.url=jdbc:postgresql://localhost:5432/Envanter
spring.datasource.username=postgres
spring.datasource.password=13285
# JPA ve Hibernate Ayarlar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# Resim Yükleme (BLOB) için Boyut Limitleri (Örn: Maksimum 5MB)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Thymeleaf Cache (Geli?tirme a?amas?nda HTML de?i?ikliklerini an?nda görmek için)
spring.thymeleaf.cache=false
